{% set version = "0.0-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rebus.datetimes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rebus.datetimes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rebus.datetimes/rebus.datetimes_{{ version }}.tar.gz
  sha256: aec17d24978bebb9f88b96940fe5fa359f8342e8312d66679d317eb443ae05c3

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rebus.base
  run:
    - r-base
    - r-rebus.base

test:
  commands:
    - $R -e "library('rebus.datetimes')"           # [not win]
    - "\"%R%\" -e \"library('rebus.datetimes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rebus.datetimes
  license: Unlimited
  summary: Build regular expressions piece by piece using human readable code. This package contains date and time functionality, and is primarily intended to be used by package developers.
  license_family: Other
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
